name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: latest
    - name: Build
      run: |
        pnmp i
        pnpm build
    - uses: actions/deploy-pages@v1
    - name: Deploy
