name: Build

on:
  push:
    branches: [ main ]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: true
      
      - name: Build
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          repository-name: vrde/www-build-website-action
          branch: main
          folder: public
          ssh-key: ${{ secrets.DEPLOY_KEY }}
